name: verifyd_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^3.4.6
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  freezed_annotation: ^2.1.0
  fyd_ui:
    git:
      url: https://github.com/fyd-tjm/Fyd-UI-KIT
  get: ^4.6.5
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  mocktail: ^0.3.0

flutter_native_splash:
  color: "#000000"
  image: assets/logo/fydLogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
