name: verifyd_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^5.0.4
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.6
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dots_indicator: ^2.1.0
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.8
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.4
  freezed_annotation: ^2.1.0
  # fyd_ui:
  #   git:
  #     url: https://github.com/fyd-tjm/Fyd-UI-KIT
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  group_button: ^5.2.2
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  lazy_load_indexed_stack: ^0.1.4
  
  marquee: ^2.2.3
  rxdart: ^0.27.6

dev_dependencies:
  
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.2
  mocktail: ^0.3.0
  logger: ^1.1.0

flutter_native_splash:
  color: "#000000"
  image: assets/logo/fydLogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
