name: verifyd_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  auto_route: ^5.0.4
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.4.4
  # connectivity_plus: ^3.0.3
  coupon_uikit: ^0.2.0
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dartz: ^0.10.1
  dots_indicator: ^2.1.0
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  # flutter_native_splash: ^2.2.8
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.3
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.1.0
  # fyd_ui:
  #   git:
  #     url: https://github.com/fyd-tjm/Fyd-UI-KIT
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  group_button: ^5.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.6.0
  lazy_load_indexed_stack: ^0.1.4
  marquee: ^2.2.3
  pinput: ^2.2.21
  rxdart: ^0.27.6
  url_launcher: ^6.1.7

dev_dependencies:
  
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.4
  json_serializable: ^6.3.2
  mocktail: ^0.3.0
  logger: ^1.1.0
  hive_generator: ^2.0.0
  # flutter_launcher_icons: ^0.11.0

# flutter_native_splash:
#   color: "#000000"
#   image: assets/logo/splash.png
#   android: true
#   ios: true
#   android_12:
#     image: assets/logo/splash.png
#     color: "#000000"

# flutter_icons:
  # image_path: "assets/icons/Group 22.png"
  # image_path_android: "assets/images/icon-710x599-android.png"
  # image_path_ios: "assets/images/icon-1024x1024.png"
  # android: true 
  # ios: true 
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # remove_alpha_ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/
    - assets/gifs/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
