name: verifyd_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animations: ^2.0.7
  auto_route: ^5.0.4
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.4.4
  cloud_functions: ^4.1.0
  connectivity_plus: ^3.0.3
  custom_navigation_bar: ^0.8.2
  dartz: ^0.10.1
  dots_indicator: ^2.1.0
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.1.0
  firebase_dynamic_links: ^5.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.3
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.6.0
  marquee: ^2.2.3
  pinput: ^2.2.21
  rxdart: ^0.27.6
  url_launcher: ^6.1.7

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.4
  json_serializable: ^6.3.2
  mocktail: ^0.3.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gifs/
    - assets/images/
    - assets/svgs/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
