name: verifyd_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  fyd_ui:
    git:
      url: https://github.com/fyd-tjm/Fyd-UI-KIT
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: assets/logo/fydLogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
