// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRICEEDcmJ9DtWaT4XhwnjrE2eAyQ5_48',
    appId: '1:989510512720:web:4680333476a4dba050a155',
    messagingSenderId: '989510512720',
    projectId: 'verifyd-store-dev',
    authDomain: 'verifyd-store-dev.firebaseapp.com',
    storageBucket: 'verifyd-store-dev.appspot.com',
    measurementId: 'G-0ZDJ0QLJV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYYDJhWLzsBn7BxP0-vPBn6rL9ksWVVTs',
    appId: '1:989510512720:android:ed6684e9ae3f446650a155',
    messagingSenderId: '989510512720',
    projectId: 'verifyd-store-dev',
    storageBucket: 'verifyd-store-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBPsveNAWMiPGYhDifg3zM_vc1p6q73BU',
    appId: '1:989510512720:ios:5f065502df0c154650a155',
    messagingSenderId: '989510512720',
    projectId: 'verifyd-store-dev',
    storageBucket: 'verifyd-store-dev.appspot.com',
    iosClientId: '989510512720-j386ds84i4qa0pacjb1c9kpjburuloka.apps.googleusercontent.com',
    iosBundleId: 'com.fydtechnologies.verifydStore',
  );
}
