// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb28_FLHuak2l0IH_ed2nK2Dzh0PsNchQ',
    appId: '1:914869368886:web:9c283f73a61fe26ebc0097',
    messagingSenderId: '914869368886',
    projectId: 'verifyd-store-prod',
    authDomain: 'verifyd-store-prod.firebaseapp.com',
    storageBucket: 'verifyd-store-prod.appspot.com',
    measurementId: 'G-NX1X6SS50F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIuo2NuKDzCnQp5Y_x8RD0nL6SOivAliw',
    appId: '1:914869368886:android:52e8e560027c5bc4bc0097',
    messagingSenderId: '914869368886',
    projectId: 'verifyd-store-prod',
    storageBucket: 'verifyd-store-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_I5bHJE2qa_uTE7bZgsTaYTpLWjigmcc',
    appId: '1:914869368886:ios:16aec97b9494514bbc0097',
    messagingSenderId: '914869368886',
    projectId: 'verifyd-store-prod',
    storageBucket: 'verifyd-store-prod.appspot.com',
    iosClientId: '914869368886-bbvnhrkouaqrl00llo6rao1b94m36o4i.apps.googleusercontent.com',
    iosBundleId: 'com.fydtechnologies.verifydStore',
  );
}
